services:
  - type: web
    name: ytmp3
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    buildFilter:
      paths:
        - app.py
        - requirements.txt
        - templates/**
        - static/**
        - render.yaml 